// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe3AVG6-13JVwszt8aiyhqOQomKuXNkes',
    appId: '1:201585203299:web:1462dc613a840e61508056',
    messagingSenderId: '201585203299',
    projectId: 'noter-3bdf8',
    authDomain: 'noter-3bdf8.firebaseapp.com',
    databaseURL: 'https://noter-3bdf8-default-rtdb.firebaseio.com',
    storageBucket: 'noter-3bdf8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAIn-GpbZCLq1UO_CWh9jZ-FC-ZxwrzwE',
    appId: '1:201585203299:android:320219fa4cd9a612508056',
    messagingSenderId: '201585203299',
    projectId: 'noter-3bdf8',
    databaseURL: 'https://noter-3bdf8-default-rtdb.firebaseio.com',
    storageBucket: 'noter-3bdf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArftytI2t67oyTglK-nVCnH94QMaSnszE',
    appId: '1:201585203299:ios:71377ca9e9d30b5f508056',
    messagingSenderId: '201585203299',
    projectId: 'noter-3bdf8',
    databaseURL: 'https://noter-3bdf8-default-rtdb.firebaseio.com',
    storageBucket: 'noter-3bdf8.firebasestorage.app',
    iosBundleId: 'com.devT.noteRing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArftytI2t67oyTglK-nVCnH94QMaSnszE',
    appId: '1:201585203299:ios:71377ca9e9d30b5f508056',
    messagingSenderId: '201585203299',
    projectId: 'noter-3bdf8',
    databaseURL: 'https://noter-3bdf8-default-rtdb.firebaseio.com',
    storageBucket: 'noter-3bdf8.firebasestorage.app',
    iosBundleId: 'com.devT.noteRing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe3AVG6-13JVwszt8aiyhqOQomKuXNkes',
    appId: '1:201585203299:web:3a34f2fea902c570508056',
    messagingSenderId: '201585203299',
    projectId: 'noter-3bdf8',
    authDomain: 'noter-3bdf8.firebaseapp.com',
    databaseURL: 'https://noter-3bdf8-default-rtdb.firebaseio.com',
    storageBucket: 'noter-3bdf8.firebasestorage.app',
  );

}